### ISSUE TITLE
Ссылки на скрипты на работают

### ISSUE THREAD

**Issue by hackoffme** [vb64/django.admin.geomap#16]
Подключил по инструкции, джанго никаких ошибок не выдает. В консоли браузера есть ошибки
GEThttps://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/build/ol.js
[HTTP/2 403 Forbidden 3289ms]
GEThttps://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/css/ol.css
[HTTP/2 403 Forbidden 4311ms]

Скрипты из базового шаблона походу не доступны 

<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/build/ol.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/css/ol.css">

**Comment by vb64** [comment]
Похду опять кто-то РФ забанил. На выходных все точно работало.

Сейчас на одном компе пашет (видимо из кэша), на ноуте нефига.

**Comment by hackoffme** [comment]
да через впн таже песня. Походу разрабы просто удалили эту версию пакета. 6.15 и 7 доступна по ссылке. С 6.15 работает
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/build/ol.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/css/ol.css" type="text/css">
с седьмой не хочет

**Comment by hackoffme** [comment]
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/build/ol.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/css/ol.css" type="text/css">

**Comment by hackoffme** [comment]
`<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/build/ol.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/css/ol.css" type="text/css">
`

**Comment by hackoffme** [comment]
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/css/ol.css

**Comment by vb64** [comment]
Ок, тогда правлю ссылки на 6.15.

На https://openlayers.org/ она стоит как официально поддерживаемая.

**Comment by hackoffme** [comment]
А статически распространять плохая идея?
{% load  static %}
<script src="{% static 'js/ol.js' %}"></script>

**Comment by vb64** [comment]
> да через впн таже песня. Походу разрабы просто удалили эту версию пакета. 6.15 и 7 доступна по ссылке. С 6.15 работает
> 
> <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/build/ol.js"></script> с седьмой не хочет

Ну или пулреквест сделайте, как инициатор. У либы будет больше контрибьюторов, и вам полюсик в карму :)

**Comment by hackoffme** [comment]
договорились :)

**Comment by vb64** [comment]
> А статически распространять плохая идея? {% load static %}
> 
> <script src="{% static 'js/ol.js' %}"></script>

Ну как-то некомильфо чужой код статически в свой проект включать. Будем надеяться, что с выходом 7.x версия 6.x больше меняться не будет и останется доступной. У них на сайте начиная с 2.х все старые версии доступны.
