### ISSUE TITLE
Auto-zoom of Admin Map?

### ISSUE THREAD

**Issue by proffalken** [vb64/django.admin.geomap#22]
First of all, thanks for such a great tool.  I've got it hooked in to WhatThreeWords on my admin panel and it's working brilliantly!

I've seen the docs about [setting the admin zoom](https://github.com/vb64/django.admin.geomap#default-map-zoom-level-and-center-of-the-map-when-displaying-a-list-of-objects-in-the-admin-panel) and I'm wondering if it's possible to have it "auto-zoom" based on the coordinates of the objects that are returned to it?

For example, if I've only got objects that have locations in central London, is it possible to have it auto-zoom to a level where all the objects are displayed on the map at a sensible level?

**Comment by vb64** [comment]
Great idea!

I'll think about the implementation.

**Comment by vb64** [comment]
> For example, if I've only got objects that have locations in central London, is it possible to have it auto-zoom to a level where all the objects are displayed on the map at a sensible level?

You can try to upgrade your installation up to version 1.3 and check out new [autozoom feature](https://github.com/vb64/django.admin.geomap#autozoom-mode).

**Comment by proffalken** [comment]
It's working perfectly! Thank you so much!
