### ISSUE TITLE
OpenStreetMap view doesn't render completely, doesn't allow zooming

### ISSUE THREAD

**Issue by wibox** [vb64/django.admin.geomap#40]
When rendering the map with all its perks in the admin panel everything works flawlessly, but when doing so in the template the visualized map looks like its a screenshot with missing chunks, and doesn't allow manual zooming (the zooming effect is the same of a picture, it just gets foggy the more i zoom in). 
View code:

def index(request):
    return render(request, 'core/index.html', geomap_context(Location.objects.all(), map_zoom="2", auto_zoom="10", map_height="1000px"))

Template code:
 <div id="my-map"> {% include "geomap/common.html" %} </div>
Enclosed in a div with an id.

I'm using django version 4.1.7

**Comment by wibox** [comment]
For anyone experiencing this, the error comes from the inclusion of multiple version of JQuery in the project. Use the one provided by their package in order to avoid such trouble.

**Comment by vb64** [comment]
Thanks for your investigation. This project is related to Django, not to js code. It's hard for me to investigate problems with js.
