### ISSUE TITLE
Template Directory

### ISSUE THREAD

**Issue by NadavK** [vb64/django.admin.geomap#5]
First, thanks for an excellent package! It was (fairly) easy to install, and bam! Instance maps!
I would like to point out that adding ```django_admin_geomap``` to ```INSTALLED_APPS``` removes the need edit ``TEMPLATES```.
I find this easier/robust because I was not able to add a template directory that supported both dev and deployment environments.

Thanks again!

**Comment by vb64** [comment]
Agree, using INSTALLED_APPS is preferable. Editing TEMPLATES present by "historical reasons" :)

I will fix the docs and example.

**Comment by vb64** [comment]
Fixed: #9
