### ISSUE TITLE
Mixin? 

### ISSUE THREAD

**Issue by sebastian-philipp** [vb64/django.admin.geomap#54]
Hi there, 

Much appreciated! You think we could have a `django_admin_geomap.ModelAdmin` as a mixin? We already use `DjangoQLSearchMixin` and `django_safedelete.SafeDeleteAdmin`. There is unfortunately a limit of classes that I can inherent from that are not Mixins.

**Comment by vb64** [comment]
Hi.

I don't know.

django_admin_geomap.ModelAdmin inherits from Django's admin.ModelAdmin and extends its changelist_view, change_view and add_view methods.

whether there will be conflicts with multiple inheritance from the classes you use - this need to check.
