### ISSUE TITLE
Pop-up on Marker Click

### ISSUE THREAD

**Issue by NadavK** [vb64/django.admin.geomap#6]
The pop-up window is not visible when clicking on a marker.
This is the HTML that changes when clicking an element:
```
<div class="popover fade bs-popover-top show" role="tooltip" id="popover906644" x-placement="top" x-out-of-boundaries="" style="position: absolute; transform: translate3d(2128px, 4041px, 0px); top: 0px; left: 0px; will-change: transform;">
<div class="arrow" style="left: 0px;">
</div><h3 class="popover-header">
</h3><div class="popover-body">ABCDEF</div></div>
```
The left position (2128) is too far right. When I change it manually to something smaller, then the pop-up does appears.
Looks like something is wrong with the pop-up position?
BTW, the top position (4041) looks to be correct.

**Comment by vb64** [comment]
I have published version 1.2 with your improvements, please update.

It also adds the ability to [run the example project on localhost](https://github.com/vb64/django.admin.geomap#usage-example).

In the admin panel of the example, I add several locations, then I click on the marker of one of them and I get the following result.

![image](https://user-images.githubusercontent.com/8738387/181515187-3f26fa74-b710-4b84-91cb-156d337a540b.png)

Does it work out differently for you?

**Comment by vb64** [comment]
Hi!

You can check out new [autozoom feature](https://github.com/vb64/django.admin.geomap#autozoom-mode) in version 1.3.

**Comment by vb64** [comment]
Let's assume the problem is solved.
