### ISSUE TITLE
geoitem_edit is not defined

### ISSUE THREAD

**Issue by JRParreno** [vb64/django.admin.geomap#62]
Not loading the openmap when in edit mode. it says in the console geoitem_edit is not define in JS

**Comment by vb64** [comment]
Try running [the example](https://github.com/vb64/django.admin.geomap#usage-example).

Then compare your code that causes the error with the example code.

**Comment by JRParreno** [comment]
thanks its working now after removing this

![image](https://github.com/user-attachments/assets/f6dfec78-0139-48b5-8cf0-7207b1b8bd95)
