### ISSUE TITLE
Admin Search/Filter

### ISSUE THREAD

**Issue by NadavK** [vb64/django.admin.geomap#7]
When using Admin Search to filter the list of items, the map still displays all items, and not just the items that the admin filtered.

**Comment by NadavK** [comment]
Proposed fix: #8

**Comment by vb64** [comment]
Thank you, this is an important improvement.

A couple of cosmetic notes for your PR, please check out.

**Comment by NadavK** [comment]
PR updated per your feedback

**Comment by vb64** [comment]
Another issue found with Python 3.7

**Comment by vb64** [comment]
Thank you again, merged #8

New release will be soon.
